spring:
  config:
    import: optional:classpath:application-secret.yml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/javitto
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  cache:
    redis:
      host: redis
      port: 6379

  elasticsearch:
    uris: http://localhost:9200

  datasource:
      username: postgres
      password: root
      url: jdbc:postgresql://localhost:5433/javitto
      driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8082

jwt:
  auth:
    converter:
      resource-id: javitto-client
      principle-attribute: preferred_username

keycloak:
  realm: javitto
  clientId: javitto-client
  secret: 9M056uTjTnUZ9LUIWYcJYFUZIZbWDJFv
  roleUser: client_user