spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/javitto
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs


  datasource:
      username: postgres
      password: root
      url: jdbc:postgresql://localhost:5432/javitto
      driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  port: 8082

jwt:
  auth:
    converter:
      resource-id: javitto-client
      principle-attribute: preferred_username

keycloak:
  realm: javitto
  clientId: javitto-client
  secret: rE0ySYD6QQyMe7xD8EJ8EA373NvAPOpc